### PR TITLE
fix nav missing avatar

### LINKED ISSUE #18: Missing avatar in `<Nav>`
After [this refactor](https://github.com/project-forms/project-forms.github.io/pull/8), the user avatar stopped appearing in `<Nav>`

### PR DESCRIPTION
**Pull request by oscard0m**
# Description
- refactor(components): `<Nav>` components expects props instead of rely on authState or Context
- test(components): add test coverage for `<Nav>` component
- fix(pages): /new passes `avatarUrl` and `onLogout` props
- refactor(app): remove unused `logout` variable

| before | after |
|--------|--------|
| image | image | 

# Context
Fixes #18

### CODE REVIEW

File: src/components/Nav.jsx [hunk 1]
```diff
@@ -7,11 +7,8 @@ import {
   StyledOcticon,
 } from "@primer/react";
 import { TableIcon } from "@primer/octicons-react";
-import useAuthState from "../hooks/use-auth-state";
-
-export default function Nav() {
-  const { authState, logout } = useAuthState();
```
Comment (oscard0m) [inline src/components/Nav.jsx:13]: @gr2m just FYI: The usage of `useAuthState` hook was not working as expected here:
- When invoking `useAuthState()`, this creates a new React state associated to this component, but is not interconnected with an upper state of the application. ([see implementation](https://github.com/project-forms/project-forms.github.io/blob/main/src/hooks/use-auth-state.js))
- This means the local variable `authState` is always empty `{ user: {} }`. `setAuthState` for this local state is never invoked.

File: src/components/Nav.jsx [hunk 2]
```diff
@@ -7,11 +7,8 @@ import {
...
 
+export default function Nav({ avatarUrl, onLogout }) {
```
Comment (oscard0m) [inline src/components/Nav.jsx:11]: @gr2m just FYI: I ended up using `props` for this component (so it's the responsibility of the parent to pass values associated to the expected `authState`).

Because it's the only occurrence of `<Nav>` component I think it makes sense using props for now. The moment we see the need to use this component in more places and passing the `props` down becomes tedious, we can migrate it to use React's [`Context`](https://react.dev/learn/passing-data-deeply-with-context).
